'''
元组：
    是Python内置的数据类型之一，是一个不可变序列
    t=('Python',120,False,3.14)
不可变序列与可变序列：
    不可变序列：
        字符串，元组：
            没有增，删，改操作
    可变序列：
        列表，字典：
            可以对序列执行增，删，改操作，对象地址不发生改变
'''
'''可变序列：列表，字典'''
lst=[10,20,30]
print(lst,id(lst))
lst.append(300)
print(lst,id(lst))
'''不可变序列：字符串，元组'''
s='hello'
print(s,id(s))
s+='world'
print(s,id(s))