#字符串被称为不可变的字符顺序
#可以使用单引号、双引号、单三引号或双三引号来定义
str1='人生苦短，我用Python'
str2="人生苦短，我用Python"
str3='''人生苦短，我用Python'''
str4="""人生苦短，我用Python"""
#单引号和双引号定义的字符串必须在同一行
#单三引号和双三引号定义的字符串可以分布在连续的多行
str5='''人生苦短，
我用Python'''
str6="""人生苦短，
我用Python"""
print(str1,type(str1))
print(str2,type(str2))
print(str3,type(str3))
print(str4,type(str4))
print(str5,type(str5))
print(str6,type(str6))
